version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mysql_phpmyadmin_web_1
      APP_PORT: 8080

  mysql_server:
    image: bureaugewas/mysql_server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  web:
    image: bureaugewas/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql_server
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "1111:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
