version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mysql-server_web_1
      APP_PORT: 8080

  web:
    image: phpmyadmin:latest
    #build:
    #  context: .
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY= 1
    depends_on:
      - db
  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=notSecureChangeMe

        #Gebleven bij: app opent op Umbrel op 8080, (nog aanpassen in umbre-app.yml), maar inloggen in phpMyAdmin lukt nog niet op 'root'@'10.21.0.23'
